name: Update data
on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm install

      # Runs a set of commands using the runners shell
      - name: Update the data
        run: |
          cd src
          node parseData.js

      - name: Deploy to GH Pages
        run: |
          git config --global user.email "mehdi.bounya@gmail.com"
          git config --global user.name "mehdibo"
          git remote set-url origin https://${{ secrets.githubToken }}@github.com/mehdibo/coronamap-ma.git
          npm run deploy
